api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Go compiler distribution version"
  homepage = "https://github.com/paketo-buildpacks/go-dist"
  id = "paketo-buildpacks/go-dist"
  keywords = ["go", "distribution", "compiler"]
  name = "Paketo Buildpack for Go Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/go-dist/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.22.*"

  [[metadata.dependencies]]
    checksum = "sha256:0fc88d966d33896384fbde56e9a8d80a305dc17a9f48f1832e061724b1719991"
    cpe = "cpe:2.3:a:golang:go:1.22.11:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.22.11?checksum=0fc88d966d33896384fbde56e9a8d80a305dc17a9f48f1832e061724b1719991&download_url=https://go.dev/dl/go1.22.11.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.22.11.src.tar.gz"
    source-checksum = "sha256:a60c23dec95d10a2576265ce580f57869d5ac2471c4f4aca805addc9ea0fc9fe"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.22.11.linux-amd64.tar.gz"
    version = "1.22.11"

  [[metadata.dependencies]]
    checksum = "sha256:4fa4f869b0f7fc6bb1eb2660e74657fbf04cdd290b5aef905585c86051b34d43"
    cpe = "cpe:2.3:a:golang:go:1.22.12:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    name = "Go"
    purl = "pkg:generic/go@go1.22.12?checksum=4fa4f869b0f7fc6bb1eb2660e74657fbf04cdd290b5aef905585c86051b34d43&download_url=https://go.dev/dl/go1.22.12.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.22.12.src.tar.gz"
    source-checksum = "sha256:012a7e1f37f362c0918c1dfa3334458ac2da1628c4b9cf4d9ca02db986e17d71"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.22.12.linux-amd64.tar.gz"
    version = "1.22.12"

  [[metadata.dependencies]]
    checksum = "sha256:535f9f81802499f2a7dbfa70abb8fda3793725fcc29460f719815f6e10b5fd60"
    cpe = "cpe:2.3:a:golang:go:1.23.10:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause", "BSD-3-Clause-Clear"]
    name = "Go"
    purl = "pkg:generic/go@go1.23.10?checksum=535f9f81802499f2a7dbfa70abb8fda3793725fcc29460f719815f6e10b5fd60&download_url=https://go.dev/dl/go1.23.10.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.23.10.src.tar.gz"
    source-checksum = "sha256:800a7ae1bff179a227b653a2f644517c800443b8b4abf3273af5e1cb7113de59"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.23.10.linux-amd64.tar.gz"
    version = "1.23.10"

  [[metadata.dependencies]]
    checksum = "sha256:80899df77459e0b551d2eb8800ad6eb47023b99cccbf8129e7b5786770b948c5"
    cpe = "cpe:2.3:a:golang:go:1.23.11:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause", "BSD-3-Clause-Clear"]
    name = "Go"
    purl = "pkg:generic/go@go1.23.11?checksum=80899df77459e0b551d2eb8800ad6eb47023b99cccbf8129e7b5786770b948c5&download_url=https://go.dev/dl/go1.23.11.linux-amd64.tar.gz"
    source = "https://go.dev/dl/go1.23.11.src.tar.gz"
    source-checksum = "sha256:296381607a483a8a8667d7695331752f94a1f231c204e2527d2f22e1e3d1247d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://go.dev/dl/go1.23.11.linux-amd64.tar.gz"
    version = "1.23.11"

  [[metadata.dependency-constraints]]
    constraint = "1.22.*"
    id = "go"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.23.*"
    id = "go"
    patches = 2

[[stacks]]
  id = "*"
